site_name: IDS FAIR Application Profile
site_url: https://example.com/
extra_css:
  - stylesheets/extra.css
  
theme:
  name: material
  icon:
    logo: material/view-comfy
  palette:
    scheme: slate
    primary: teal
  features:
    - navigation.tabs
    - navigation.top

repo_url: https://github.com/fair-data-spaces/ids-fair-ap
copyright: © Copyright 2021, Fraunhofer
edit_uri: ""   
markdown_extensions:
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.tabbed
  - pymdownx.highlight
  - pymdownx.superfences
  - admonition

nav:
  - Introduction: index.md
  - Classes:
      - Data Resource: classes/data_resource.md
      - CSV File: classes/csv_file.md